AWSTemplateFormatVersion: 2010-09-09
Description: Script para automatizar o processo de criação de um Bucket S3
Parameters:
  BucketName:
    Type: String
    Description: Nome do Bucket S3

Metadata:
  AWS::CloudFormation::Interface:
    ParametersGroup:
      - Label: Label
        default: Bucket S3
    Parameters:
      - BucketName
    ParametersLabel:
      BucketName: BucketName
      default: "Nome do meu Bucket: "

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
